## NumPy 

**NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

**Numpy is also incredibly fast, as it has bindings to C libraries. For more information on why you would want to use Arrays instead of lists in python, check out this [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

**We will only learn the basics of NumPy, to get started we need to install it!
 

## Installation Instructions

**In the first lecture (tutorials), we have learned to install the Anaconda and basics of jupyter**


**Again, for use NyumPy, I would highly recommend you to install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    conda install numpy
    
**If you do not have Anaconda yet and can not install it, please refer to [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**



## Using NumPy

Once you've installed NumPy you can import it as a library:

In [4]:
import numpy as np #note this abbreviation np is a conventional one;  


Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors, arrays, matrices, and number generation as data science and machine learning play a lot with these concepts which often represent model paramter or the data matrix. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).


Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [5]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [4]:
np.array(my_list)

array([1, 2, 3])

In [8]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]

In [9]:
np.array(my_matrix)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [14]:
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### zeros and ones

Generate arrays of zeros or ones

In [15]:
np.zeros(4)

array([0., 0., 0., 0.])

In [17]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
np.ones(2)

array([1., 1.])

In [20]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [24]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [13]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [25]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

## eye

Creates an identity matrix, the notation here eye corresponds to the math notation $\mathbf{I}$

In [27]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [29]:
np.random.rand(5)

array([0.56130476, 0.4083865 , 0.71532621, 0.11956809, 0.6778241 ])

In [30]:
np.random.rand(5,2)

array([[0.91016912, 0.89540986],
       [0.60791819, 0.32475055],
       [0.74513438, 0.54174244],
       [0.81355644, 0.76604723],
       [0.97219377, 0.35023307]])

### randn

Return a sample (or samples) from the "standard normal" distribution 
$$\mathcal{N}(0,1) ~~\hbox{with pdf }   p(x) = {1\over \sqrt{2\pi}} e^{-x^2\over 2}$$

In [20]:
np.random.randn(10)

array([ 1.77447882,  0.44023699, -0.54631826, -0.92202451, -2.57109167,
       -0.82681815, -1.60036539,  1.40740541, -0.29074952,  0.77838961])

In [32]:
a = np.random.randn(1000)

In [33]:
a.shape

(1000,)

In [34]:
 np.mean(a)

0.004498675899550403

In [35]:
np.std(a)

0.9843834798032672

In [36]:
amatrix = np.random.randn(5,5)

In [37]:
amatrix[1,2]

-0.40925493327529433

In [38]:
 amatrix

array([[-0.94821036,  0.40340016, -0.21026334,  0.83170829,  0.32718741],
       [ 0.83576914,  0.48779976, -0.40925493, -0.93493408, -0.06779045],
       [-0.31434124,  0.6889826 ,  0.2194607 , -0.30781494,  0.35610486],
       [-0.0635478 ,  0.09059241,  0.97436453,  0.79427568,  2.35178437],
       [ 0.52359792,  0.48883061, -0.08556159, -1.15497027,  1.8472699 ]])

In [40]:
np.size(amatrix)

25

In [42]:
np.shape(amatrix)

(5, 5)

In [40]:
areshape = np.reshape(amatrix,25)

In [41]:
np.shape(areshape)

(25,)

In [52]:
np.size(areshape)


25

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

Example: np.random.randint(1,6) means to generate a random integre between 1 and 5 where each integer has prob 0.2

In [49]:
np.random.randint(1,6) 

5

In [50]:
np.random.randint(1,100,2)

array([95, 15])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [52]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [53]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [54]:
ranarr

array([48, 12,  2, 45, 10, 31, 24,  4, 46, 42])

## Reshape
Returns an array containing the same data with a new shape.

In [55]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [57]:
ranarr

array([48, 12,  2, 45, 10, 31, 24,  4, 46, 42])

In [66]:
ranarr.max()

48

In [59]:
ranarr.argmax() # index of max 

0

In [60]:
ranarr.min()

2

In [61]:
ranarr.argmin()

2

## Shape

Shape is an attribute that arrays have (not a method):

In [62]:
# Vector
arr.shape

(25,)

In [68]:
arr.size

25

In [81]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [82]:
arr.reshape(1,25).shape

(1, 25)

In [83]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [69]:
arr.reshape(25,1).shape

(25, 1)

### dtype

You can also grab the data type of the object in the array:

In [85]:
arr.dtype

dtype('int64')

In [70]:
ranarr.dtype

dtype('int64')